first_project/urls.py
from django.contrib import admin
from django.urls import path
from start_app import views
from django.conf.urls import include

urlpatterns = [
    path('start_app/', include('start_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

start_app/urls.py
from django.urls import path
from start_app import views

app_name = 'start_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('relative/',views.relative, name='relative'),
    path('other/',views.other, name='other'),
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login, name='user_login'),
]

start_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class Access(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class UserInfo(models.Model):
    first_name = models.CharField(max_length=264, unique=True)
    last_name = models.CharField(max_length=264, unique=True)
    email = models.CharField(max_length=264, unique=True)

    # def __str__(self):
    #     return str(self.first_name), str(self.last_name), str(self.email)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    
    def __str__(self):
        return self.user.username

start_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from .models import UserInfo, UserProfileInfo


# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     confirm_email = forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)
#     # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, 
#     #                             validators=[validators.MaxLengthValidator(0)])

#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         cemail = all_clean_data['confirm_email']

#         if email != cemail:
#             raise forms.ValidationError("Make sure Emails Match!")

class NewUserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

start_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from start_app.models import Topic, Webpage, Access
from start_app.forms import NewUserForm, UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

# def index(request):
#     webpages_list = Access.objects.order_by('date')
#     my_dict = {'access_records':webpages_list}
#     return render(request,'start_app/index.html', context=my_dict)

# def user_details(request):
#     form = NewUserForm()
#     if request.method == 'POST':
#         form = NewUserForm(request.POST)

#         if form.is_valid():
#             form.save(commit=True)
#             return index(request)
#         else:
#             print("Invalid Form")
#     return render(request,'start_app/users.html', {'form' : form})

# def form_name_view(request):
#     form = FormName()

#     if request.method == 'POST':
#         form = forms.FormName(request.POST)

#         if form.is_valid():
#             print("Validation Success")
#             print("Name :"+ form.cleaned_data['name'])
#             print("Email :"+ form.cleaned_data['email'])
#             print("Text :"+ form.cleaned_data['text'])

#     return render(request,'start_app/form_page.html', {'form':form})

def index(request):
    context_dict = {'text':'Hello World', 'number':100}
    return render(request, 'start_app/index.html', context_dict)

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('start_app:index'))

def other(request):
    return render(request, 'start_app/other.html')

def relative(request):
    return render(request, 'start_app/relative_url.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'start_app/register.html', {'user_form':user_form, 
                                                        'profile_form':profile_form,
                                                        'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('start_app:index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'start_app/login.html',{})    

templates/start_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a  class="navbar-brand" href="{% url 'start_app:index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'start_app:other' %}">Other</a></li>
                <!-- <li><a class="navbar-link" href="{% url 'start_app:register' %}">Register</a></li> -->
                
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'start_app:register' %}">Register</a></li>
                <li><a class="navbar-link" href="{% url 'start_app:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>

</body>
</html>

templates/start_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <h1>Fill out the form</h1>
    <div class="container">
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class ="btn btn-primary" value="Submit">
        </form>

    </div>
</body>
</html>

templates/start_app/index.html
<!DOCTYPE html>
{% extends "start_app/base.html" %}

    {% block body_block %} 
    <h1>Welcome to Index Page </h1>
    <!-- <h2> Go to /users to fill the form </h2> -->
    <h1>Django Level Five</h1>
   <h1> {{ text|cut:'World' }} </h1>
   <h1> {{ number|add:"99" }} </h1>
    {% endblock %}

templates/start_app/login.html
{% extends 'start_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1> Please Login </h1>
        <form action="{% url 'start_app:user_login' %}" method="POST" >
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">    
        </form>
    </div>

{% endblock %}

templates/start_app/other.html
<!DOCTYPE html>
{% extends "start_app/base.html" %}

    {% block body_block %} 
    <h1>Welcome to Others Page</h1>

    {% endblock %}

templates/start_app/register.html
<!DOCTYPE html>
{% extends "start_app/base.html" %}
{% load static %}
{% block body_block %} 
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for Registering</h1>
            {% else %}
                <h1>Register Here!</h1>
                <h3>Fill out the form</h3>

                <form  enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" value="Register">
                </form>
        {% endif %}
   </div> 
{% endblock %}

templates/start_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Welcome to relative </h1>
    <a href="{% url 'start_app:other' %}">The other Page </a>
    <a href="{% url 'admin:index' %}">Admin index</a>
</body>
</html>

templates/start_app/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Records</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>Please Sign Up here!</h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class = 'btn btn-primary' value="Submit">
        </form> 
    </div>
</body>
</html>